#!/usr/bin/env bash

pushd `dirname $0` > /dev/null
ROOTPATH=`pwd -P`
popd > /dev/null

NAME=setup-etcd-peers-environment
VERSION=0.1.3
PREFIX=${NAME}-${VERSION}

mkdir -p $ROOTPATH/bin
cd $ROOTPATH/src/github.com/glerchundi/setup-etcd-peers-environment

GOPATH=$ROOTPATH/vendor:$ROOTPATH \
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 \
  go build -o $ROOTPATH/bin/${PREFIX}-darwin-amd64 -a -tags netgo -installsuffix cgo -ldflags '-extld ld -extldflags -static' -a -x .

GOPATH=$ROOTPATH/vendor:$ROOTPATH \
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
  go build -o $ROOTPATH/bin/${PREFIX}-linux-amd64 -a -tags netgo -installsuffix cgo -ldflags '-extld ld -extldflags -static' -a -x .


